import { test, expect } from '@playwright/test';

test.describe('AI Insights E2E (mocked WebSocket)', () => {
  test('app loads and can receive mocked websocket messages', async ({ page }) => {
    // navigate to root
    await page.goto('/');

    // inject a WebSocket mock that simulates a server pushing an insight
    await page.addInitScript(() => {
      // Replace the global WebSocket with a simple mock during tests
      const RealWS = (window as any).WebSocket;
      class MockSocket {
        onopen: any = null;
        onmessage: any = null;
        onclose: any = null;
        readyState = 1;
        constructor(url: string) {
          // simulate open
          setTimeout(() => this.onopen && this.onopen({}), 50);
          // send a test message after open
          setTimeout(() => {
            const payload = JSON.stringify({
              id: 'e2e-1',
              severity: 'info',
              title: 'E2E insight',
              summary: 'Generated by Playwright mock',
              timestamp: new Date().toISOString(),
            });
            this.onmessage && this.onmessage({ data: payload });
          }, 150);
        }
        send() {}
        close() {
          this.readyState = 3;
          this.onclose && this.onclose({});
        }
      }
      // only override if not already mocked
      try {
        (window as any).WebSocket = MockSocket as any;
        (window as any).OriginalWebSocket = RealWS;
      } catch (e) {
        // ignore in restricted envs
      }
    });

    // trigger any UI that opens the AI Insights tray if your app exposes a keyboard
    // or button. This is an example that clicks an element with aria-label "Open AI Insights" if present.
    const openBtn = await page.locator('[aria-label="Open AI Insights"]');
    if (await openBtn.count()) {
      await openBtn.click();
    }

    // wait for the mocked insight to appear in the DOM
    await expect(page.locator('text=E2E insight')).toBeVisible({ timeout: 5000 });
  });
});
